### ISSUE TITLE
There was an unexpected error (type=Forbidden, status=403). Access Denied

### ISSUE THREAD

**Issue by SitanSIme** [zohar001/lottery#3]
您好，就是我用您现在的代码打包之后（修改数据库后），访问8088端口时出现如下问题：
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Aug 29 10:44:14 CST 2019
There was an unexpected error (type=Forbidden, status=403).
Access Denied
请问是我配置的问题吗?还是需要需改一些什么。

**Comment by zohar001** [comment]
最新版本没问题了
